version: '3'
services:
  todofront:
    image: todofrontend
    restart: always
    build:
      context: ./todo-app/front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST: todobackend
    depends_on:
      - todobackend
  todoback:
    image: todobackend
    restart: always
    build:
      context: ./todo-app/back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  todotests:
    image: todotests
    restart: always
    build:
      context: ./todo-app/tests
      dockerfile: Dockerfile
    environment:
      - FRONT-HOST: todofrontend
    depends_on:
      - todofrontend
      - todobackend